server:
  port: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
spring:
  application:
    name: at-crowd-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
  session:
    store-type: redis
aliyun:
  oss:
    access-key-id: LTAI"*************"
    access-key-secret: "*************"
    bucket-domain: http"*************"
    bucket-name: jw2021"
    end-point: http://o"*************"