server:
  port: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
spring:
  application:
    name: at-crowd-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
  session:
    store-type: redis
aliyun:
  oss:
    access-key-id: LTAI4GKTr7A2xJNErs8fS1bJ
    access-key-secret: 7bqohh0RvHYsKPXSq8xeQUn3EsFsL6
    bucket-domain: http://jw2021.oss-cn-hangzhou.aliyuncs.com
    bucket-name: jw2021
    end-point: http://oss-cn-hangzhou.aliyuncs.com