server:
  port: 4000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
spring:
  application:
    name: at-crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
  session:
    store-type: redis
short:
  message:
    host: "https://intlsms.market.alicloudapi.com"
    path: "/comms/sms/sendmsgall"
    method: "post"
    appCode: "aad14596b0814f028a940470c30528d8"
    templateID: "0000000"
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

