server:
  port: 4000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
spring:
  application:
    name: at-crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html