server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
spring:
  application:
    name: at-crowd-zuul
  redis:
    host: 127.0.0.1
  session:
    store-type: redis
zuul:
  ignored-services: "*"
  sensitive-headers: "*" # 在 Zuul 向其他微服务重定向时保持原本头信息（请求头、响应 头）
  routes:
    crowd-portal:
      service-id: at-crowd-auth
      path: /** # 这里一定要使用两个“*”号，不然“/”路径后面的多层路径将无法访问
    crowd-project:
      service-id: at-crowd-project
      path: /project/**
    crowd-order:
      service-id: at-crowd-order
      path: /order/**
    crowd-pay:
      service-id: at-crowd-pay
      path: /pay/**
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000